---
title: "16.3"
output: html_document
author: Margit Dahl sørensen, Hermann Moen 
editor_options: 
output: html_document 
  chunk_output_type: console
---
## 16.3 
```{r}
library(exscidata); library(tidyverse); library(dplyr)
data("hypertrophy")
glimpse(hypertrophy)


Testo_DXA <- hypertrophy %>%
  select(PARTICIPANT, DXA_LBM_T1:DXA_LBM_T3, TESTOSTERONE_T1:TESTOSTERONE_T3) %>%
  rowwise() %>%
  mutate(testoavg. = mean(c(TESTOSTERONE_T1, TESTOSTERONE_T2, TESTOSTERONE_T3), na.rm=TRUE)) %>%

  ungroup() %>%
  mutate(DXA_change = DXA_LBM_T3 - DXA_LBM_T1) %>%
  group_by() %>%
  select(PARTICIPANT, testoavg., DXA_change) %>%
  filter(! is.nan(testoavg.)) %>%
  
  print()
  
  
# Fit the model

reg <- lm(DXA_change ~ testoavg., data = Testo_DXA) %>%

summary(reg) %>%
  print()


#Reg

library(broom) 

tidy(reg) %>%
  print()
 

#plotte figur

Testo_DXA %>%
  ggplot(aes(testoavg., DXA_change)) + geom_point(shape = 19) + theme_minimal() + geom_smooth(method = "lm") + labs(x = "Gjennomsnittlig testosteron", y = "Endring i DXA") 

print()

```

##16.3 
I datasettet hypertrophy finner vi flere forskjellige variabler tilknyttet muskelvekst. Blandt annet finnes det en måling av deltakernes testosteron verdier ved tre tidspunkt fra intervensjonen, og mager kroppsmasse målt i DXA ved tre tidspunkter. Vi ville se på en eventuell korrelasjon mellom den gjennomsnittlige testosteronverdien  og endringen i mager kroppsmasse fra test 1 til 3. 

Testosterone er et potent anabolsk hormon, som stimulerer muskel protein syntesen[1,2], og forbedrer intramuskulært opptak av aminosyrer,[3] som sammen resulterer i en forbedring i total protein balanse.[4] Basert på dette ser vi for oss at testosteron nivået, vil ha en positiv innvirkning på endringen i mager kroppsmasse.  

# Regresjon
Vi så for oss en sammenheng mellom gjennomsnittlig testosteron verdi, og endringen i mager kroppsmasse. Vi tenkte korrelasjonen skulle være positiv, altså mere testosteron, ville resultere i større økning i mager masse. Dette er basert på litteratur nevnt over. Det viste seg at for hver verdi med testosteron ville den magre kroppsmassen endres med -0,00434, p=0,0157. 
Vi ønsker å vite om dette resultatet er noe vi kan stole på, og dermed kunne late som at funnet her er en sannhet. Vi må derfor kunne si noe om hvor reliabelt det er, og hvor sannsynlig det er at forskjellen i dataen skyldes sammenhengen mellom variablene og ikke støy. Standard feil er et estimat på reliabiliteten til dataene. Reliabiliteten kan forklares som hvor stor verdien til den tilfeldige variasjonen i et mål vil være fra gang til gang, når målet er gjort under like forhold (hopkins,2000) Standardfeilen beregnes ved hjelp av «within subject standard deviation». Dette datasettet ga oss en standardfeil i målingene på 0,00167. 

Nå vet vi hvor mye som kan forventes skyldes støy, og vi ønsker nå å vite om funnet vårt om korrelasjonen er noe vi kan late som er sant.  Til dette vil vi bruke p-verdi. P-verdien forteller oss hvor overraskende utfallet er hvis null hypotesen er sann. Altså vil det være et veldig overraskende funn hvis null hypotesen var sann, og vi kan kalle funnet statistisk signinfikant p</=0,05, når signifikans grensen er satt til 0,05. Det betyr at i denne situasjonen kan vi late som at funnet er sant. 

Altså vet vi nå at det er et veldig overraskende funn om null hypotesen er sann, som i praksis gjør at vi kan late som at funnet er sant, da den som nevnt var under grenseverdien for statistisk signifikans. Vi kan også se på om null hypotesen skal avises eller følges ved hjelp av t-verdi. T-verdien er enkelt sagt forholdet mellom verdien og standardfeilen. Jo høyere verdien er, jo sikrere kan vi være på at null hypotesen kan avvises. Dette gjøres i hypotesetesting i students t-test.  Et akseptabelt resultat i t-verdi er 2, eller -2. I dette tilfellet her var t-verdien 2,60, som gir oss enda en grunn til å late som at funnet vil være sant i alle tilfeller.  
