---
title: "lac"
author: "Håvard Crantz Lorentzen"
date: "28 9 2021"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE, }
library(tidyverse)
library(readxl)
library(ggplot2)


lactate <- read_excel("data til laktatprofil.xlsx", na="NA")


lactate %>%
  # Select columns needed for analysis
  select(FP, time, lac.75:lac.300) %>%
  # Only one participant and time-point
  filter(time == "pre", FP == 6) %>%
  # Pivot to long format data using the lactate columns
  pivot_longer(names_to = "watt", 
               values_to = "lactate", 
               names_prefix = "lac.",
               names_transform = list(watt = as.numeric),
               cols = lac.75:lac.300) %>%
   # Remove NA (missing) values to avoid warning/error messages.
  filter(!is.na(lactate))%>%
  # Plot the data, group = subject needed to connect the points
  ggplot(aes(watt, lactate, group = FP))  + 
  geom_line(lty = 2) +
  geom_point(shape = 21, fill = "lightblue", size = 2.5) +
# Adding straight lines at specific values
  geom_hline(yintercept = 4, color = "red") +
  geom_vline(xintercept = 341.5, color = "blue") + # Adding a straight line from a linear model
  geom_smooth(method = "lm", se = FALSE, formula = y ~ x, color = "#e41a1c") +

 # Adding a polynomial linear model to the plot
  
  # poly(x, 2) add a second degree polynomial model.
  geom_smooth(method = "lm", se = FALSE, formula = y ~ poly(x, 2), color = "#377eb8") +
  # poly(x, 3) add a third degree polynomial model.
  geom_smooth(method = "lm", se = FALSE, formula = y ~ poly(x, 3), color = "#4daf4a") +
  # poly(x, 4) add a forth degree polynomial model.
  geom_smooth(method = "lm", se = FALSE, formula = y ~ poly(x, 4), color = "#ff7f00") 

```


```{r}
library(tidyverse)
library(readxl)
library(ggplot2)

lactate <- read_excel("data til laktatprofil.xlsx", na="NA")

lactate1 <- lactate %>%
  # Select columns needed for analysis
  select(FP, time, lac.75:lac.300) %>%
  # Only one participant and time-point
  filter(time == "pre", FP == 6) %>%
  # Pivot to long format data using the lactate columns
  pivot_longer(names_to = "watt", 
               values_to = "lactate", 
               names_prefix = "lac.",
               names_transform = list(watt = as.numeric),
               cols = lac.75:lac.300) %>%
   # Remove NA (missing) values to avoid warning/error messages.
  filter(!is.na(lactate))

# fit "straight line" model
m1 <- lm(lactate ~ watt, data = lactate1)

# fit second degree polynomial
m2 <- lm(lactate ~ poly(watt, 2, raw = TRUE), data = lactate1)

# fit third degree polynomial
m3 <- lm(lactate ~ poly(watt, 3, raw = TRUE), data = lactate1)

# fit forth degree polynomial
m4 <- lm(lactate ~ poly(watt, 4, raw = TRUE), data = lactate1)

# Store all residuals as new variables
lactate1$resid.m1 <- resid(m1)
lactate1$resid.m2 <- resid(m2)
lactate1$resid.m3 <- resid(m3)
lactate1$resid.m4 <- resid(m4)

lactate1 %>%
  # gather all the data from the models
  pivot_longer(names_to = "model", 
               values_to = "residual", 
               names_prefix = "resid.", 
               names_transform = list(residual = as.numeric), 
               cols = resid.m1:resid.m4) %>%
  # Plot values with the observed watt on x axis and residual values at the y
  ggplot(aes(watt, residual, fill = model)) + geom_point(shape = 21, size = 3) +
  
  # To set the same colors/fills as above we use scale fill manual
  scale_fill_manual(values = c("#e41a1c", "#377eb8", "#4daf4a", "#ff7f00"))


#new data data frame
ndf <- data.frame(watt = seq(from = 125, to = 275, by = 0.1)) # high resolution, we can find the nearest10:th a watt

ndf$predictions <- predict(m4, newdata = ndf)

lactate_threshold4 <- ndf %>%
  filter(abs(predictions - 4) == min(abs(predictions - 4)))
 
lactate_threshold2 <- ndf %>%
  filter(abs(predictions - 2) == min(abs(predictions - 2)))
```

```{r}

lactate <- read_excel("data til laktatprofil.xlsx", na="NA")

lactate2 <- lactate %>%
  select(FP, time, lac.75:lac.300) %>%
  pivot_longer(names_to = "watt", 
               values_to = "lactate", 
               names_prefix = "lac.", 
              names_transform = list(watt = as.numeric), 
              cols = lac.75:lac.300) %>%
  filter(FP == 6, 
         time == "pre", 
         !is.na(lactate)) %>% # Remove NA values
  print()

# Fit the model 
model <- lm(lactate ~ watt + I(watt^2) + I(watt^3), data = lactate2)


# Predict lactate values over all observed watt values
# calculate the smallest distance from the fixed lactate value 

new_data <- data.frame(watt = seq(from = min(lactate2$watt), to = max(lactate2$watt), by = 0.1))

new_data$dist <- abs(predict(model, newdata = new_data) - 4)

# Find the smallest value of predicted - fixed lacate value
new_data %>%
  filter(dist == min(dist)) # Where the dist value equals the minimum dist value
lt <- function(data) {
  
  # Fit a 3 degree polynomial model
  m <- lm(lactate ~ watt + I(watt^2) + I(watt^3), data = data)
  
  # Store a data frame with exercise intensities
  new_data <- data.frame(watt = seq(from = min(data$watt), to = max(data$watt), by = 0.01))
  
  # Predict using the new data, predicting lactate values at each 
  new_data$pred <- predict(m, newdata = new_data)
  
  # calculate deviation from the lactate value of interest
  new_data$watt.4mmol <- abs(new_data$pred - 4)
  new_data$watt.2mmol <- abs(new_data$pred - 2)

  # Create a results data frame
  results <- data.frame(watt.4mmol = new_data[which.min(new_data$watt.4mmol),1], watt.2mmol = new_data[which.min(new_data$watt.2mmol),1])

  # Return the data frame
  return(results)
  
}


lactate3 <- lactate %>%
  select(FP, time, lac.75:lac.300) %>%
  pivot_longer(names_to = "watt", 
               values_to = "lactate", 
               names_prefix = "lac.", 
              names_transform = list(watt = as.numeric), 
              cols = lac.75:lac.300) %>%
  filter(!is.na(lactate)) %>% # Remove NA values
  group_by(time, FP) %>%
   mutate(n = n()) %>%
  filter(n >= 4) %>%
  # Use grouup modify to apply the function to all participants per time-point (and group)
  group_modify(~ lt(.)) %>%
  print()

```

```{r}
lactate4 <- lactate3 %>%
  group_by(FP) %>%
  mutate(n = n()) %>%
  filter(n == 2) %>%
pivot_wider(names_from = time, values_from = c(watt.4mmol, watt.2mmol)) %>%
    print()

    
TE4 <- lactate4 %>%
  mutate(diff = watt.4mmol_post - watt.4mmol_pre) %>% 
  ungroup() %>%
  # Change/difference score
  summarise(s = sd(diff, na.rm = TRUE), # Summarize to calculate sd, and... 
            m = mean(c(watt.4mmol_post, watt.4mmol_pre)), # mean
            te = s / sqrt(2), 1, # the typical error.
            cv = 100 * (te / m), 1, 
            L = qt(0.975, 4) * s) %>%  # Calculate as a percentage of the mean
  print()

TE2 <- lactate4 %>%
  mutate(diff = watt.2mmol_post - watt.2mmol_pre) %>% 
   ungroup() %>%# Change/difference score
  summarise(s = sd(diff),  # Summarize to calculate sd, and... 
            m = mean(c(watt.2mmol_post, watt.2mmol_pre)), # mean
            te = s / sqrt(2), 1, # the typical error.
            cv = 100 * (te / m), 1, 
            L = qt(0.975, 4) * s) # Calculate as a percentage of the mean


  cv4 <- round(TE4$cv, 2)
  cv2 <- round(TE2$cv, 2)
  
```

## Resultater  
Typefeil er ved 4mmol laktat er `r cv4`% og ved 2mmol laktat er den `r cv2`%

```{r}
# Create a data frame of known distances and molecular weights
ladder <- data.frame(dist = c(29, 43.5, 60.5,
                              80.5, 106.5,  141.5,  
                              181.5,    243.5,  281.5,
                              328.5,    390.5,  465.5,  580.5), 
                     mw = c(1000, 900, 800, 
                            700, 600, 500,
                            400, 300, 250, 
                            200, 150, 100, 50))
            

# Create a new data frame of unknowns
unknown <- data.frame(dist = c(470.5,   391.5,  528.5,
                               421.5,   507.5))


 #Fit the model
cal <- lm(log(mw) ~ dist, data = ladder)

# Check model performance, R^2 should be ~ 1.
summary(cal)

## 
## Call:
## lm(formula = log(mw) ~ dist, data = ladder)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.054731 -0.040851 -0.001577  0.034241  0.063743 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  6.9957281  0.0200403  349.08  < 2e-16 ***
## dist        -0.0052316  0.0000712  -73.47 3.69e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.0432 on 11 degrees of freedom
## Multiple R-squared:  0.998,  Adjusted R-squared:  0.9978 
## F-statistic:  5398 on 1 and 11 DF,  p-value: 3.691e-16

preds <- exp(predict(cal, newdata = unknown)
             
             
```



